class Global_Vars:
    model = []
    Images = []
    Feat = []
    Target = []
    Video = []
    Feat_1 = []
    Feat_2 = []
    Feat_3 = []
    Feat_4 = []
    Feat = []
    learnperc = None
    Train_Data = []
    Train_Target = []
    Test_Data = []
    Test_Target = []
    pun = []
    data = []